### PR TITLE
Add new hud to main repo

### PR DESCRIPTION
**Pull request by osztenkurden**
If you agree, I'd like to add this HUD to main repo

### CODE REVIEW

**Comment by osztenkurden** [comment]
@tusa162

**Comment by Lummppy** [comment]
Their is a problem running the HUD the observer overlay HUD when I try to run it , it says to unable to connect to my ip something something and then when I click more it says check the node.js firewall and proxy setting I try to do it but same errors

**Comment by Lummppy** [comment]
How should I talk to you bro?

**Review by antuness1 — APPROVED** [review]

**Comment by emil6156** [comment]
Any of you, that know how to add ADR stats to the HUD?
I personal like this setup:
https://dribbble.com/shots/6218323-CS-GO-custom-hud

**Comment by Ejay2287** [comment]
@emil6156 ADR doesn't seem to be possible as the calculation for ADR is "complete damage you did / rounds played" and at the moment as we can only count rounds but not player damage per round to do the ADR calculation.  Future Request?

**Comment by emil6156** [comment]
Ah, okay :/ 
Some kind of Extra Stats in Buytime could be awsome - Would that be a possibility?
Just testing the Vesper v2 edition - Seems like the Bo3/Bo5 aint working probably? :) 
Maybe a box showing with the current caster name/Tournament somewhere?

I really want to get a custom made HUD for my stream, but im shit at coding xD
LOVE all your work in here!

**Review by LukasW1337 — APPROVED** [review]

**Comment by ohneflachs** [comment]
@Ejay2287 The patchnotes from 15.08.2018 say:
 – Game state integration includes a field “round_totaldmg” to track total damage the player dealt.
So it should be possible

**Comment by Ejay2287** [comment]
@ohneflachs Oh okay, I was just going off the data on the create a hud section and didn't see that field there. You should be able to use that field along with the number of rounds played then display that on your overlay then @emil6156

**Review by bjerrecs — APPROVED** [review]

**Comment by luisfranjoso** [comment]
Vesper 2 is nice but has a small bug with team names and images when names are longer.
Probably a quick fix

image

**Comment by ohneflachs** [comment]
@tusa162
Just saw you made the space just bigger, wouldn't it be a safer way to use:
overflow: hidden;
white-space: nowrap;

Just in case someone is using "Super long awesome powerful Team" as team name? 
2ac6dc2d3d 1

Imo rather cut it off than bug away.

**Comment by xxTeDYxx** [comment]
:<

image

**Pull request closed without merging**
